-- TABLE: BALLOON_EVENT_LINKS (イベント対象風船)
CREATE TABLE IF NOT EXISTS BALLOON_EVENT_LINKS (
  event_id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_EVENT_LINKS DROP CONSTRAINT IF EXISTS fk_BALLOON_EVENT_LINKS_GUERRILLA_EVENTS;
ALTER TABLE BALLOON_EVENT_LINKS ADD CONSTRAINT fk_BALLOON_EVENT_LINKS_GUERRILLA_EVENTS FOREIGN KEY (event_id) REFERENCES GUERRILLA_EVENTS(id) ON DELETE CASCADE;
ALTER TABLE BALLOON_EVENT_LINKS DROP CONSTRAINT IF EXISTS fk_BALLOON_EVENT_LINKS_BALLOONS;
ALTER TABLE BALLOON_EVENT_LINKS ADD CONSTRAINT fk_BALLOON_EVENT_LINKS_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: GUERRILLA_EVENTS (ゲリライベント)
CREATE TABLE IF NOT EXISTS GUERRILLA_EVENTS (
  id uuid NOT NULL,
  title text NOT NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK

-- INDEX


-- TABLE: BALLOON_REPORTS (通報)
CREATE TABLE IF NOT EXISTS BALLOON_REPORTS (
  id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  reporter_user_id uuid NOT NULL,
  reason  NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_REPORTS DROP CONSTRAINT IF EXISTS fk_BALLOON_REPORTS_USERS;
ALTER TABLE BALLOON_REPORTS ADD CONSTRAINT fk_BALLOON_REPORTS_USERS FOREIGN KEY (reporter_user_id) REFERENCES USERS(id) ON DELETE CASCADE;
ALTER TABLE BALLOON_REPORTS DROP CONSTRAINT IF EXISTS fk_BALLOON_REPORTS_BALLOONS;
ALTER TABLE BALLOON_REPORTS ADD CONSTRAINT fk_BALLOON_REPORTS_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: BALLOON_POP_HISTORY (割れ履歴)
CREATE TABLE IF NOT EXISTS BALLOON_POP_HISTORY (
  id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  popped_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_POP_HISTORY DROP CONSTRAINT IF EXISTS fk_BALLOON_POP_HISTORY_BALLOONS;
ALTER TABLE BALLOON_POP_HISTORY ADD CONSTRAINT fk_BALLOON_POP_HISTORY_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: CONTRIBUTION_LEDGER (貢献台帳)
CREATE TABLE IF NOT EXISTS CONTRIBUTION_LEDGER (
  id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE CONTRIBUTION_LEDGER DROP CONSTRAINT IF EXISTS fk_CONTRIBUTION_LEDGER_USERS;
ALTER TABLE CONTRIBUTION_LEDGER ADD CONSTRAINT fk_CONTRIBUTION_LEDGER_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL;
ALTER TABLE CONTRIBUTION_LEDGER DROP CONSTRAINT IF EXISTS fk_CONTRIBUTION_LEDGER_BALLOONS;
ALTER TABLE CONTRIBUTION_LEDGER ADD CONSTRAINT fk_CONTRIBUTION_LEDGER_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: BALLOON_PROGRESS (風船進捗)
CREATE TABLE IF NOT EXISTS BALLOON_PROGRESS (
  id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  current_need  NOT NULL,
  current_amount  NOT NULL,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_PROGRESS DROP CONSTRAINT IF EXISTS fk_BALLOON_PROGRESS_BALLOONS;
ALTER TABLE BALLOON_PROGRESS ADD CONSTRAINT fk_BALLOON_PROGRESS_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: BALLOON_SELECTIONS (選択中風船)
CREATE TABLE IF NOT EXISTS BALLOON_SELECTIONS (
  user_id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  selected_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_SELECTIONS DROP CONSTRAINT IF EXISTS fk_BALLOON_SELECTIONS_USERS;
ALTER TABLE BALLOON_SELECTIONS ADD CONSTRAINT fk_BALLOON_SELECTIONS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;
ALTER TABLE BALLOON_SELECTIONS DROP CONSTRAINT IF EXISTS fk_BALLOON_SELECTIONS_BALLOONS;
ALTER TABLE BALLOON_SELECTIONS ADD CONSTRAINT fk_BALLOON_SELECTIONS_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: BALLOON_MEMBERSHIPS (参加情報)
CREATE TABLE IF NOT EXISTS BALLOON_MEMBERSHIPS (
  id uuid NOT NULL,
  balloon_id uuid NOT NULL,
  user_id uuid NOT NULL,
  joined_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOON_MEMBERSHIPS DROP CONSTRAINT IF EXISTS fk_BALLOON_MEMBERSHIPS_BALLOONS;
ALTER TABLE BALLOON_MEMBERSHIPS ADD CONSTRAINT fk_BALLOON_MEMBERSHIPS_BALLOONS FOREIGN KEY (balloon_id) REFERENCES BALLOONS(id) ON DELETE CASCADE;
ALTER TABLE BALLOON_MEMBERSHIPS DROP CONSTRAINT IF EXISTS fk_BALLOON_MEMBERSHIPS_USERS;
ALTER TABLE BALLOON_MEMBERSHIPS ADD CONSTRAINT fk_BALLOON_MEMBERSHIPS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: BALLOONS (風船)
CREATE TABLE IF NOT EXISTS BALLOONS (
  id uuid NOT NULL,
  type  NOT NULL,
  owner_user_id uuid NOT NULL,
  is_public  NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE BALLOONS DROP CONSTRAINT IF EXISTS fk_BALLOONS_USERS;
ALTER TABLE BALLOONS ADD CONSTRAINT fk_BALLOONS_USERS FOREIGN KEY (owner_user_id) REFERENCES USERS(id) ON DELETE SET NULL;

-- INDEX


-- TABLE: TASK_TAGS (タスクタグ)
CREATE TABLE IF NOT EXISTS TASK_TAGS (
  task_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE TASK_TAGS DROP CONSTRAINT IF EXISTS fk_TASK_TAGS_TASKS;
ALTER TABLE TASK_TAGS ADD CONSTRAINT fk_TASK_TAGS_TASKS FOREIGN KEY (task_id) REFERENCES TASKS(id) ON DELETE CASCADE;
ALTER TABLE TASK_TAGS DROP CONSTRAINT IF EXISTS fk_TASK_TAGS_TAGS;
ALTER TABLE TASK_TAGS ADD CONSTRAINT fk_TASK_TAGS_TAGS FOREIGN KEY (tag_id) REFERENCES TAGS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: TAGS (タグ)
CREATE TABLE IF NOT EXISTS TAGS (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE TAGS DROP CONSTRAINT IF EXISTS fk_TAGS_USERS;
ALTER TABLE TAGS ADD CONSTRAINT fk_TAGS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: TASK_COMPLETIONS (タスク完了履歴)
CREATE TABLE IF NOT EXISTS TASK_COMPLETIONS (
  id uuid NOT NULL,
  task_id uuid NOT NULL,
  user_id uuid NOT NULL,
  completed_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE TASK_COMPLETIONS DROP CONSTRAINT IF EXISTS fk_TASK_COMPLETIONS_TASKS;
ALTER TABLE TASK_COMPLETIONS ADD CONSTRAINT fk_TASK_COMPLETIONS_TASKS FOREIGN KEY (task_id) REFERENCES TASKS(id) ON DELETE CASCADE;
ALTER TABLE TASK_COMPLETIONS DROP CONSTRAINT IF EXISTS fk_TASK_COMPLETIONS_USERS;
ALTER TABLE TASK_COMPLETIONS ADD CONSTRAINT fk_TASK_COMPLETIONS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: TASKS (タスク)
CREATE TABLE IF NOT EXISTS TASKS (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  due_at timestamptz NOT NULL,
  is_done  NOT NULL,
  done_at  NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE TASKS DROP CONSTRAINT IF EXISTS fk_TASKS_USERS;
ALTER TABLE TASKS ADD CONSTRAINT fk_TASKS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: TRANSFER_TOKENS (引き継ぎ発行)
CREATE TABLE IF NOT EXISTS TRANSFER_TOKENS (
  id uuid NOT NULL,
  token  NOT NULL,
  issuer_device_id  NOT NULL,
  consumer_device_id  NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE TRANSFER_TOKENS DROP CONSTRAINT IF EXISTS fk_TRANSFER_TOKENS_USER_DEVICES;
ALTER TABLE TRANSFER_TOKENS ADD CONSTRAINT fk_TRANSFER_TOKENS_USER_DEVICES FOREIGN KEY (issuer_device_id) REFERENCES USER_DEVICES(id) ON DELETE SET NULL;
ALTER TABLE TRANSFER_TOKENS DROP CONSTRAINT IF EXISTS fk_TRANSFER_TOKENS_USER_DEVICES;
ALTER TABLE TRANSFER_TOKENS ADD CONSTRAINT fk_TRANSFER_TOKENS_USER_DEVICES FOREIGN KEY (consumer_device_id) REFERENCES USER_DEVICES(id) ON DELETE SET NULL;

-- INDEX


-- TABLE: USER_SESSIONS (セッション)
CREATE TABLE IF NOT EXISTS USER_SESSIONS (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  device_id uuid NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE USER_SESSIONS DROP CONSTRAINT IF EXISTS fk_USER_SESSIONS_USERS;
ALTER TABLE USER_SESSIONS ADD CONSTRAINT fk_USER_SESSIONS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;
ALTER TABLE USER_SESSIONS DROP CONSTRAINT IF EXISTS fk_USER_SESSIONS_USER_DEVICES;
ALTER TABLE USER_SESSIONS ADD CONSTRAINT fk_USER_SESSIONS_USER_DEVICES FOREIGN KEY (device_id) REFERENCES USER_DEVICES(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: USER_DEVICES (端末)
CREATE TABLE IF NOT EXISTS USER_DEVICES (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  device_key  NOT NULL,
  device_name text NOT NULL,
  push_token  NOT NULL,
  last_used_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE USER_DEVICES DROP CONSTRAINT IF EXISTS fk_USER_DEVICES_USERS;
ALTER TABLE USER_DEVICES ADD CONSTRAINT fk_USER_DEVICES_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: USER_IDENTITIES (認証リンク)
CREATE TABLE IF NOT EXISTS USER_IDENTITIES (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  provider smallint NOT NULL,
  provider_uid  NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE USER_IDENTITIES DROP CONSTRAINT IF EXISTS fk_USER_IDENTITIES_USERS;
ALTER TABLE USER_IDENTITIES ADD CONSTRAINT fk_USER_IDENTITIES_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: USER_SETTINGS (ユーザー設定)
CREATE TABLE IF NOT EXISTS USER_SETTINGS (
  user_id uuid NOT NULL,
  render_quality smallint NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK
ALTER TABLE USER_SETTINGS DROP CONSTRAINT IF EXISTS fk_USER_SETTINGS_USERS;
ALTER TABLE USER_SETTINGS ADD CONSTRAINT fk_USER_SETTINGS_USERS FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE;

-- INDEX


-- TABLE: USERS (ユーザー)
CREATE TABLE IF NOT EXISTS USERS (
  id uuid NOT NULL,
  handle text NOT NULL,
  plan smallint NOT NULL,
  is_guest boolean NOT NULL,
  auth_state smallint NOT NULL,
  last_login_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  deleted_at timestamptz NOT NULL,
  PRIMARY KEY ()
);

-- FK

-- INDEX


